wordpress:
 image: wordpress
 working_dir: /var/www/html
 links:
 - db:mysql
 ports:
 - 80:80
 volumes:
 - /var/WORDPRESS/WP-CONTENT:/var/www/html/wp-content
 - /var/WORDPRESS/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

db:
 image: mariadb
 environment:
 - MYSQL_ROOT_PASSWORD=BayesianAveragingModel15
 volumes:
 - /var/WORDPRESS/DB:/var/lib/mysql

